coverage:
  status:
    project:
      default:
        target: 80.0
        threshold: 0.5
    patch:
      default:
        target: 80.0
        threshold: 2.0
      cli:
        target: 55.0
        threshold: 5.0
        paths:
          - src/cli/
